name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout

        uses: actions/checkout@v2
        with:
          path: master
      - name: Deployment

        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.SSH_HOST }}

          username: ${{ secrets.SSH_USERNAME }}

          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /var/www/html/demo
            php artisan down --message "Application is now in maintenance mode."
            git pull
            sudo chown -R $USER:www-data storage bootstrap/cache
            # sudo chown -R $USER:www-data bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            php artisan up
